// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
  LoginLoginPostData,
  LoginLoginPostResponse,
  LogoutLogoutPostResponse,
  SendForgotPasswordPasswordForgotPostData,
  SendForgotPasswordPasswordForgotPostResponse,
  ResetPasswordPasswordResetPostData,
  ResetPasswordPasswordResetPostResponse,
  RegisterRegisterPostData,
  RegisterRegisterPostResponse,
  RefreshAccessTokenTokenRefreshPostResponse,
  GetUserRefreshTokensTokensMeGetResponse,
  RevokeUserRefreshTokenTokensMeTokenIdDeleteData,
  RevokeUserRefreshTokenTokensMeTokenIdDeleteResponse,
  HealthCheckUtilsHealthGetResponse,
  VersionUtilsVersionGetResponse,
  SendVerificationEmailVerificationEmailGetData,
  SendVerificationEmailVerificationEmailGetResponse,
  VerifyEmailVerificationEmailTokenGetData,
  VerifyEmailVerificationEmailTokenGetResponse,
} from './types.gen'

export class AuthService {
  /**
   * Login
   * Login a user and return an access token.
   *
   * Args:
   * response (Response): The response object.
   * request (Request): The request object.
   * ip_address (str): The client IP address.
   * session (AsyncSession): The database session.
   * form_data (OAuth2PasswordRequestForm): The form data.
   *
   * Returns:
   * Token: The access token.
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginLoginPost(
    data: LoginLoginPostData
  ): CancelablePromise<LoginLoginPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/login',
      formData: data.formData,
      mediaType: 'application/x-www-form-urlencoded',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Logout
   * Logout current user.
   *
   * Args:
   * session (AsyncSession): The database session.
   * consumed_refresh_token (RefreshToken): The consumed refresh token.
   *
   * Returns:
   * dict: The logout message.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static logoutLogoutPost(): CancelablePromise<LogoutLogoutPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/logout',
    })
  }

  /**
   * Send Forgot Password
   * Send a password reset email.
   *
   * Args:
   * session (AsyncSession): The database session.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.usernameEmail
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static sendForgotPasswordPasswordForgotPost(
    data: SendForgotPasswordPasswordForgotPostData
  ): CancelablePromise<SendForgotPasswordPasswordForgotPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/password/forgot',
      query: {
        username_email: data.usernameEmail,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Reset Password
   * Reset user password.
   *
   * Args:
   * session (AsyncSession): The database session.
   * token (str): The password reset token.
   * body (ResetPassword): Body containing the new password.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPasswordPasswordResetPost(
    data: ResetPasswordPasswordResetPostData
  ): CancelablePromise<ResetPasswordPasswordResetPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/password/reset',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Register
   * Register a new user.
   *
   * Args:
   * request (Request): The request object.
   * session (AsyncSession): The database session.
   * user (UserCreate): The user data.
   *
   * Returns:
   * UserPublic: The user data.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerRegisterPost(
    data: RegisterRegisterPostData
  ): CancelablePromise<RegisterRegisterPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/register',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Refresh Access Token
   * Refresh the access and refresh token.
   *
   * Args:
   * response (Response): The response object.
   * ip_address (str): The client IP address.
   * session (AsyncSession): The database session.
   * consumed_refresh_token (RefreshToken): The consumed refresh token.
   *
   * Returns:
   * Token: The access token.
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static refreshAccessTokenTokenRefreshPost(): CancelablePromise<RefreshAccessTokenTokenRefreshPostResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/token/refresh',
    })
  }
}

export class TokensService {
  /**
   * Get User Refresh Tokens
   * Get the current user refresh tokens.
   *
   * Args:
   * session (AsyncSession): The database session.
   * user_token (TokenData): The user's token data.
   *
   * Returns:
   * RefreshTokensPublic: The current user sessions.
   * @returns RefreshTokensPublic Successful Response
   * @throws ApiError
   */
  public static getUserRefreshTokensTokensMeGet(): CancelablePromise<GetUserRefreshTokensTokensMeGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/tokens/me',
    })
  }

  /**
   * Revoke User Refresh Token
   * Revoke a user refresh token.
   *
   * Args:
   * session (AsyncSession): The database session.
   * user_token (TokenData): The user's token data.
   * token_id (UUID): The refresh token id.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.tokenId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static revokeUserRefreshTokenTokensMeTokenIdDelete(
    data: RevokeUserRefreshTokenTokensMeTokenIdDeleteData
  ): CancelablePromise<RevokeUserRefreshTokenTokensMeTokenIdDeleteResponse> {
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/tokens/me/{token_id}',
      path: {
        token_id: data.tokenId,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UtilsService {
  /**
   * Health Check
   * Health check endpoint.
   *
   * Returns:
   * bool: True
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheckUtilsHealthGet(): CancelablePromise<HealthCheckUtilsHealthGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/health',
    })
  }

  /**
   * Version
   * Get the API version.
   *
   * Returns:
   * str: The API version.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static versionUtilsVersionGet(): CancelablePromise<VersionUtilsVersionGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/version',
    })
  }
}

export class VerificationService {
  /**
   * Send Verification Email
   * Send verification email.
   *
   * Args:
   * session (AsyncSession): The database session.
   * email (str): The email address to send the verification email to.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static sendVerificationEmailVerificationEmailGet(
    data: SendVerificationEmailVerificationEmailGetData
  ): CancelablePromise<SendVerificationEmailVerificationEmailGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/verification/email',
      query: {
        email: data.email,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Verify Email
   * Verify email address.
   *
   * Args:
   * session (AsyncSession): The database session.
   * token (str): The verification token.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.token
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static verifyEmailVerificationEmailTokenGet(
    data: VerifyEmailVerificationEmailTokenGetData
  ): CancelablePromise<VerifyEmailVerificationEmailTokenGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/verification/email/{token}',
      path: {
        token: data.token,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }
}
