// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_post = {
  client_id?: string | null
  client_secret?: string | null
  grant_type?: string | null
  password: string
  scope?: string
  username: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type RefreshTokenPublic = {
  created_at?: string
  expires_at: string
  id: string
  ip_address: string
  last_used_at?: string
  user_id: string
}

export type RefreshTokensPublic = {
  count: number
  refresh_tokens: Array<RefreshTokenPublic>
}

export type ResetPassword = {
  new_password: string
  token: string
}

export type Token = {
  access_token: string
  token_type: string
}

export type UserCreate = {
  email: string
  password: string
  username: string
}

export type UserPublic = {
  created_at?: string
  disabled?: boolean
  email: string
  id: string
  role?: UserRole
  username: string
  verified?: boolean
}

export type UserRole = 'user' | 'admin' | 'root'

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type LoginLoginPostData = {
  formData: Body_login_login_post
}

export type LoginLoginPostResponse = Token

export type LogoutLogoutPostResponse = Message

export type SendForgotPasswordPasswordForgotPostData = {
  usernameEmail: string
}

export type SendForgotPasswordPasswordForgotPostResponse = Message

export type ResetPasswordPasswordResetPostData = {
  requestBody: ResetPassword
}

export type ResetPasswordPasswordResetPostResponse = Message

export type RegisterRegisterPostData = {
  requestBody: UserCreate
}

export type RegisterRegisterPostResponse = UserPublic

export type RefreshAccessTokenTokenRefreshPostResponse = Token

export type GetUserRefreshTokensTokensMeGetResponse = RefreshTokensPublic

export type RevokeUserRefreshTokenTokensMeTokenIdDeleteData = {
  tokenId: string
}

export type RevokeUserRefreshTokenTokensMeTokenIdDeleteResponse = Message

export type HealthCheckUtilsHealthGetResponse = boolean

export type VersionUtilsVersionGetResponse = string

export type SendVerificationEmailVerificationEmailGetData = {
  email: string
}

export type SendVerificationEmailVerificationEmailGetResponse = Message

export type VerifyEmailVerificationEmailTokenGetData = {
  token: string
}

export type VerifyEmailVerificationEmailTokenGetResponse = Message
