// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
  GetRolesManagementRolesGetResponse,
  GetUserDataManagementUsersGetData,
  GetUserDataManagementUsersGetResponse,
  UpdateRoleManagementUsersUserIdRolePatchData,
  UpdateRoleManagementUsersUserIdRolePatchResponse,
  MyDetailsMeGetResponse,
  UpdatePasswordMePasswordPatchData,
  UpdatePasswordMePasswordPatchResponse,
  UpdateUsernameMeUsernamePatchData,
  UpdateUsernameMeUsernamePatchResponse,
  HealthCheckUtilsHealthGetResponse,
  VersionUtilsVersionGetResponse,
} from './types.gen'

export class ManagementService {
  /**
   * Get Roles
   * Get the available roles.
   *
   * Args:
   * user_token (TokenData): The user's token data.
   *
   * Returns:
   * list: The available roles.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static getRolesManagementRolesGet(): CancelablePromise<GetRolesManagementRolesGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/management/roles',
    })
  }

  /**
   * Get User Data
   * Get the user data.
   *
   * Args:
   * session (AsyncSession): The database session.
   * user_token (TokenData): The user's token data.
   * username_email (str): The username or email of the user.
   *
   * Returns:
   * UserPublic: The user data.
   * @param data The data for the request.
   * @param data.usernameEmail
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static getUserDataManagementUsersGet(
    data: GetUserDataManagementUsersGetData
  ): CancelablePromise<GetUserDataManagementUsersGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/management/users',
      query: {
        username_email: data.usernameEmail,
      },
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Role
   * Update the user role.
   *
   * Args:
   * session (AsyncSession): The database session.
   * user_token (TokenData): The user's token data.
   * user_id (UUID): The user ID to update.
   * body (UpdateUserRole): The request body containing the new role.
   *
   * Returns:
   * bool: True
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updateRoleManagementUsersUserIdRolePatch(
    data: UpdateRoleManagementUsersUserIdRolePatchData
  ): CancelablePromise<UpdateRoleManagementUsersUserIdRolePatchResponse> {
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/management/users/{user_id}/role',
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UsersService {
  /**
   * My Details
   * Get the current user details.
   *
   * Args:
   * session (AsyncSession): The database session.
   * user_token (TokenData): The user's token data.
   *
   * Returns:
   * UserPublic: The current user details.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static myDetailsMeGet(): CancelablePromise<MyDetailsMeGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/me',
    })
  }

  /**
   * Update Password
   * Update the current user password.
   *
   * Args:
   * session (AsyncSession): The database session.
   * body (UpdatePassword): The request body.
   * user_token (TokenData): The user's token data.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMePasswordPatch(
    data: UpdatePasswordMePasswordPatchData
  ): CancelablePromise<UpdatePasswordMePasswordPatchResponse> {
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/me/password',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }

  /**
   * Update Username
   * Update the current user username.
   *
   * Args:
   * session (AsyncSession): The database session.
   * body (UpdateUsername): The request body.
   * user_token (TokenData): The user's token data.
   *
   * Returns:
   * Message: The response message.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updateUsernameMeUsernamePatch(
    data: UpdateUsernameMeUsernamePatchData
  ): CancelablePromise<UpdateUsernameMeUsernamePatchResponse> {
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/me/username',
      body: data.requestBody,
      mediaType: 'application/json',
      errors: {
        422: 'Validation Error',
      },
    })
  }
}

export class UtilsService {
  /**
   * Health Check
   * Health check endpoint.
   *
   * Returns:
   * bool: True
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheckUtilsHealthGet(): CancelablePromise<HealthCheckUtilsHealthGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/health',
    })
  }

  /**
   * Version
   * Get the API version.
   *
   * Returns:
   * str: The API version.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static versionUtilsVersionGet(): CancelablePromise<VersionUtilsVersionGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/version',
    })
  }
}
