// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UpdateUsername = {
  new_username: string
}

export type UpdateUserRole = {
  new_role: string
}

export type UserPublic = {
  created_at?: string
  disabled?: boolean
  email: string
  id: string
  role?: UserRole
  username: string
  verified?: boolean
}

export type UserRole = 'user' | 'admin' | 'root'

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type GetRolesManagementRolesGetResponse = Array<string>

export type GetUserDataManagementUsersGetData = {
  usernameEmail: string
}

export type GetUserDataManagementUsersGetResponse = UserPublic

export type UpdateRoleManagementUsersUserIdRolePatchData = {
  requestBody: UpdateUserRole
  userId: string
}

export type UpdateRoleManagementUsersUserIdRolePatchResponse = Message

export type MyDetailsMeGetResponse = UserPublic

export type UpdatePasswordMePasswordPatchData = {
  requestBody: UpdatePassword
}

export type UpdatePasswordMePasswordPatchResponse = Message

export type UpdateUsernameMeUsernamePatchData = {
  requestBody: UpdateUsername
}

export type UpdateUsernameMeUsernamePatchResponse = Message

export type HealthCheckUtilsHealthGetResponse = boolean

export type VersionUtilsVersionGetResponse = string
