/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutResetPasswordImport } from './routes/_layout/reset-password'
import { Route as LayoutForgotPasswordImport } from './routes/_layout/forgot-password'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResetPasswordRoute = LayoutResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutForgotPasswordRoute = LayoutForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/forgot-password': {
      preLoaderRoute: typeof LayoutForgotPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reset-password': {
      preLoaderRoute: typeof LayoutResetPasswordImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutForgotPasswordRoute,
    LayoutResetPasswordRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
