// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise'
import { OpenAPI } from './core/OpenAPI'
import { request as __request } from './core/request'
import type {
  HealthCheckUtilsHealthGetResponse,
  VersionUtilsVersionGetResponse,
} from './types.gen'

export class UtilsService {
  /**
   * Health Check
   * Health check endpoint.
   *
   * Returns:
   * bool: True
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheckUtilsHealthGet(): CancelablePromise<HealthCheckUtilsHealthGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/health',
    })
  }

  /**
   * Version
   * Get the API version.
   *
   * Returns:
   * str: The API version.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static versionUtilsVersionGet(): CancelablePromise<VersionUtilsVersionGetResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/utils/version',
    })
  }
}
